// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentProject.Concretes;

#nullable disable

namespace StudentProject.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20221024085814_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("StudentProject.Concretes.Student", b =>
                {
                    b.Property<int>("StudentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentNumber");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentProject.Concretes.StudentScore", b =>
                {
                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("Lesson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Score");

                    b.HasIndex("StudentNumber");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("StudentProject.Concretes.StudentScore", b =>
                {
                    b.HasOne("StudentProject.Concretes.Student", "Student")
                        .WithMany("Scores")
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentProject.Concretes.Student", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
